[package]
name = "sudo"
version = "0.1.0-alpha.1"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
sudo-common.workspace = true
sudo-system.workspace = true
sudo-cli.workspace = true
sudoers.workspace = true
sudo-pam.workspace = true
